name: 'Update DB'

on:
  schedule:
    - cron:  '0 3 1,6,11,16,21,26 * *'
  push:
    branches:
      - main

env:
  DATABASE_CODE: DB3LITEBINIPV6

jobs:
  update-db:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: wget -O "/var/tmp/IP_DB.zip" "https://www.ip2location.com/download/?token=${{ secrets.IP2LOCATION_TOKEN }}&file=${{ env.DATABASE_CODE }}"

      - name: Unzip
        run: unzip /var/tmp/IP_DB.zip -d /var/tmp/IP_DB

      - name: Replace
        run: mv -f /var/tmp/IP_DB/IP2LOCATION-LITE-DB3.IPV6.BIN public/assets/IP_DB.BIN

      - name: Save
        uses: stefanzweifel/git-auto-commit-action@v5